### ISSUE TITLE
百度网盘访问不了了

### ISSUE THREAD

**Issue by jcyao** [codemayq/chinese_chatbot_corpus#17]

**Comment by codemayq** [comment]
可能是部分内容涉嫌违禁，待更新新的下载源

**Comment by daiyuding** [comment]
现在又下载不了了，大佬

**Comment by codemayq** [comment]
> 现在又下载不了了，大佬

raw_chat_corpus
https://www.aliyundrive.com/s/qXBdAYtz5j5
提取码: 81ao
点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
