### ISSUE TITLE
下载点已失效

### ISSUE THREAD

**Issue by chiangandy** [codemayq/chinese_chatbot_corpus#8]
您好～对您的整理完的训练材料非常感兴趣，但baidu下载点已失效，是否方便可以提供google drive的载点？万分感谢

**Comment by chiangandy** [comment]
说明一下，下载点失效是指整理好的下载语料的载点，谢谢

**Comment by codemayq** [comment]
感谢你的关注。
你好，可能是因为这个下载点是大陆特有的原因。Google Drive 我需要处理一下，处理好后，会更新，并在这里留言，预期2天内。

**Comment by chiangandy** [comment]
万分感谢～



codingma ***@***.***> 於 2021年3月10日 週三 下午5:55寫道：

**Comment by codemayq** [comment]
https://drive.google.com/file/d/1So-m83NdUHexfjJ912rQ4GItdLvnmJMD/view?usp=sharing

上传了，还请试一下

**Comment by chiangandy** [comment]
可以了，感谢协助
江謝迪


codingma ***@***.***> 於 2021年3月12日 週五 上午11:34寫道：
